= jpdfbookmarks-test-pdf-examples
life888888
:doctype: article
:encoding: utf-8
:lang: zh
:toc: left
:numbered:
:experimental:
:cn-example-file: README-zh_CN
:jp-example-file: README-jp
:tw-example-file: README-zh_TW
:en-example-file: README

這個專案是用來產生 jpdfbookmarks 的測試基準的 PDF。

== System Requirement

* JDK
* Maven 3.6+

== 如何產生測試基本用的 PDF

[IMPORTANT] 
.注意
==== 

* 第一次執行時需要一點下載時間。因為需要下載所需要的字型。
** 下載的字型會放在 使用者的 Home 之下的 `downloaded-resources`。
** 下載的字型以及 Theme 包含 簡體中文(CN) , 繁體中文(TW) , 日文(JP) , 韓文(KR)。
** 可以修改 asciidoctor-pdf-cjk-resources/pom.xml 把不需要的語言部分給註解掉不下載。
* 預設會一次產出四種語言的測試 PDF(簡體中文(CN) , 繁體中文(TW) , 日文(JP) , 韓文(KR)) , 如果不需要四種語言的 PDF , 可以修改 asciidoctor-pdf-cjk-examples/pom.xml 把不需要的語言部分給註解掉不產出。
====

轉換 asciidoc 到 PDF 可以使用 `process-resources` goal (設定在  pom.xml 的 預設 goal):

[source,bash]
----
$ mvn
# 或者是這個
$ mvn -P pdf-include
----

* Maven Profile： pdf-include , 是設定 讓 README_XX.adoc 會去 include CHANGELOG.adoc。

產出的 PDF 檔案請參閱 <<file-list,產出檔案清單>>




[source,bash]
----
$ mvn -P pdf-default
----

* Maven Profile： pdf-default, 是設定 讓 README_XX.adoc 不會去 include CHANGELOG.adoc。

產出的 PDF 檔案請參閱 <<file-list,產出檔案清單>>



[source,bash]
----
$ mvn -P pdf-compress
----

* Maven Profile： pdf-compress, 是設定 產出 PDF 啟用壓縮。測試後，發現有設定壓縮選項的 PDF 檔案大小可以減少 25%。

產出的 PDF 檔案請參閱 <<file-list,產出檔案清單>>

[source,bash]
----
$ mvn -P pdf-compress-include
----

* Maven Profile： pdf-compress-include, 是設定 讓 README_XX.adoc 會去 include CHANGELOG.adoc。並且 PDF 啟用壓縮。測試後，發現有設定壓縮選項的 PDF 檔案大小可以減少 25%。

產出的 PDF 檔案請參閱 <<file-list,產出檔案清單>>

== 差異

與 asciidoctor-maven-examples/asciidoctor-pdf-cjk-example 官方原版的差異:

* 把 下載 CJK 字型 fonts 與 themes 拆出成為 asciidoctor-pdf-cjk-resources maven module
* 把 下載的位置改為 使用者 Home 目錄下的 downloaded-resources。
* 避免每次執行都要不斷下載　CJK 字型 fonts 與 themes。
* 增加　asciidoctor-pdf-cjk-examples/README.adoc 英文版本, 作為非 CJK 語系的 PDF 對照組。
* 增加  asciidoctor-pdf-cjk-examples/README-zh_TW.adoc, 由 README-zh_CN.adoc 修改而來。
* 修改 README-jp.adoc , README-zh_CN.adoc , README-zh_TW.adoc 關於 asciidoc INCLUDE 的部分。
* 增加 PDF 壓縮的選項。

[#file-list]
== 產出檔案清單

[source,bash]
----
asciidoctor-pdf-cjk-examples/target
├── generated-docs
│   ├── README-jp.pdf
│   ├── README.pdf
│   ├── README-zh_CN.pdf
│   └── README-zh_TW.pdf
├── generated-docs-compress
│   ├── README-jp.pdf
│   ├── README.pdf
│   ├── README-zh_CN.pdf
│   └── README-zh_TW.pdf
├── generated-docs-compress-include
│   ├── README-jp.pdf
│   ├── README.pdf
│   ├── README-zh_CN.pdf
│   └── README-zh_TW.pdf
└── generated-docs-include
    ├── README-jp.pdf
    ├── README.pdf
    ├── README-zh_CN.pdf
    └── README-zh_TW.pdf
----

== Maven Module

把 asciidoctor-pdf-cjk-example 拆分成為:

* asciidoctor-pdf-cjk-resources
* asciidoctor-pdf-cjk-examples-pdf

簡化 asciidoctor-pdf-cjk-example pom.xml 太龐大的問題。

===  asciidoctor-pdf-cjk-resources

負責下載 CJK 需要的字型 fonts , Themes

=== asciidoctor-pdf-cjk-examples-pdf

負責處理 PDF 的轉換 , 需要相依  asciidoctor-pdf-cjk-resources。


== jpdfbookmarks 測試報告

針對 jpdfbookmarks 開啟 本專案的 pdf 的測試結果 , 整理於 

jpdfbookmarks-test-reports_zh_TW.adoc
